### ISSUE TITLE
Project needs a proper licence

### ISSUE THREAD

**Issue by Gymnasiast** [zrowny/OpenRCT2-OpenGraphics#3]
There isn't currently a licence for this project. To avoid any troubles later on, it should have one. I would advise to look at similar projects to see what kind of licences are common for this sort of thing. If there is any doubt between multiple ones: I would generally recommend taking one that is as permissive as possible, but you can always ask.

**Comment by ccoors** [comment]
For OpenRCT2-OpenMusic I chose CC-BY-SA-4.0. Although the final audio files may be a bit more restrictive, depending on which sample set I'll use.

**Comment by zrowny** [comment]
Meant to put this under GPL v3.0 a while ago.
