### ISSUE TITLE
Output images have too many digits for the numbers

### ISSUE THREAD

**Issue by zrowny** [zrowny/OpenRCT2-OpenGraphics#4]
At the moment, the `compile` script outputs final images with a static 5 digits for their numbers, as such:

`pic00000.bmp, pic00001.bmp, ...`

This causes issues with using RideMaker, since it expects images to have the lowest necessary digits for the ride (i.e., a ride with 300 images would need images with only 3 digits, `picXXX.bmp`), and it won't replace the first 10 images, leaving the originals.

**Comment by PFCKrutonium** [comment]
It won't replace the first 10, and requires that numbering scheme? Yikes, I have to wonder what the internal code looks like.

**Comment by zrowny** [comment]
Somehow it manages to realize what it's done wrong on pic00010.bmp and includes the rest of them fine. Buggy made the source code available [for download](http://www.interactivitiesink.com/rct2/) if you have any interest.

**Comment by PFCKrutonium** [comment]
http://www.interactivitiesink.com/rct2/download.cgi?loc=ridecode.zip

Well, I took a look, and I dunno.

**Comment by zrowny** [comment]
Ahh, I found the relevant code

````
CString str;
for (i = 0; i < num_images; i++)
{
	str.Format("pic%d.bmp",i);
	InsertBitmap(i,str);
	str.Format("pic0%d.bmp",i);
	InsertBitmap(i,str);
	str.Format("pic00%d.bmp",i);
	InsertBitmap(i,str);
	str.Format("pic000%d.bmp",i);
	InsertBitmap(i,str);
	# Snipped
}
````

Basically it tries to insert every bitmap into the DAT file (starting with 0) by trying out 4 versions of each image filename, with 0-3 padded zeros (InsertBitmap() simply returns if the filename doesn't exist). Evidently, it won't work for the first 10 images if I'm using fixed 5 digits, since the first 10 images will have *4* padded zeros. This means that RideMaker technically won't work to use a fixed digit length for the MultiDimensional Coaster, since it has more than 10,000 images. However, we don't have to use a consistent numbering scheme, so we don't actually have to use a fixed digit length at all, so `pic1.bmp, pic2.bmp,...pic10.bmp` should work, or even `pic0001.bmp, pic02.bmp, pic3.bmp, pic004.bmp...`.

I think it makes the most sense for the script to just remove the padding from filenames when creating the finished images.

**Comment by zrowny** [comment]
Whoops
